version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: hw02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres